-- Migración de Historial de Solicitudes - COMECyT
-- Corrección: Evitar NULL en fecha_actualizacion (es NOT NULL)

-- Asegurar administradores
INSERT INTO administradores (id, nombre, email, password_hash, rol, activo, fecha_creacion)
VALUES 
(7, 'VICTOR', 'victor@comecyt.gob.mx', '$2y$10$legacy_hash', 'revisor', true, NOW()),
(8, 'RICARDO', 'ricardo@comecyt.gob.mx', '$2y$10$legacy_hash', 'revisor', true, NOW())
ON CONFLICT (id) DO NOTHING;

INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2025-0001', 'sistemas', 'GERARDO ARRIAGA CAMACHO', 'migracion@comecyt.gob.mx', 'Beca_Tesis', 'media', 'CAMBIOS EN SISTEMA (Medio: correo)', 'completada', 'VICTOR', '2025-12-19 10:00:00', '2026-01-07 10:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0001', 'sistemas', 'GERARDO ARRIAGA CAMACHO', 'migracion@comecyt.gob.mx', 'INTERNACIONAL', 'media', 'Bloqueo de sitio (Medio: correo)', 'completada', 'RICARDO', '2026-01-07 10:00:00', '2026-01-07 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0002', 'sistemas', 'GERARDO ARRIAGA CAMACHO', 'migracion@comecyt.gob.mx', 'Estancias', 'media', 'Bloqueo de sitio (Medio: correo)', 'completada', 'RICARDO', '2026-01-07 10:00:00', '2026-01-07 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0003', 'sistemas', 'GERARDO ARRIAGA CAMACHO', 'migracion@comecyt.gob.mx', 'Beca_Tesis', 'media', 'Apertura de candados (Medio: correo)', 'completada', 'VICTOR', '2026-02-08 10:00:00', '2026-02-08 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0004', 'sistemas', 'GERARDO ARRIAGA CAMACHO', 'migracion@comecyt.gob.mx', 'Beca_Tesis', 'media', 'DISPERSIÓN MASIVA (Medio: correo)', 'completada', 'VICTOR', '2026-02-08 10:00:00', '2026-02-09 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0005', 'sistemas', 'JAQUELINE RAMIREZ GARCIA', 'migracion@comecyt.gob.mx', 'DUAL', 'media', 'DISPERSIÓN MASIVA (Medio: correo)', 'completada', 'VICTOR', '2026-01-12 10:00:00', '2026-01-12 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0006', 'sistemas', 'ANA GABRIELA SIERRA SANCHEZ', 'migracion@comecyt.gob.mx', 'ESYCA', 'media', 'DISPERSIÓN MASIVA (Medio: correo)', 'completada', 'RICARDO', '2026-01-14 10:00:00', '2026-01-14 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0007', 'sistemas', 'ABRIL FLORES CASTORENA', 'migracion@comecyt.gob.mx', 'Sitio web', 'media', 'Bloqueo de sitio (Medio: correo)', 'completada', 'ABRIL', '2026-01-16 10:00:00', '2026-01-16 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0008', 'sistemas', 'JAQUELINE RAMIREZ GARCIA', 'migracion@comecyt.gob.mx', 'DUAL', 'media', 'DISPERSIÓN MASIVA (Medio: correo)', 'completada', 'ABRIL', '2026-01-19 10:00:00', '2026-01-23 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0009', 'sistemas', 'STEPHANIE MIRANDA RODRIGUEZ', 'migracion@comecyt.gob.mx', 'SAEPI', 'media', 'Bloqueo de sitio (Medio: correo)', 'completada', 'ABRIL', '2026-01-13 10:00:00', '2026-01-21 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0010', 'sistemas', 'ANA GABRIELA SIERRA SANCHEZ', 'migracion@comecyt.gob.mx', 'ESTANCIAS', 'media', 'Bloqueo de sitio (Medio: correo)', 'completada', 'ABRIL', '2026-01-28 10:00:00', '2026-01-28 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0011', 'sistemas', 'CARLOS ROBERTO GONZALEZ CORNEJO', 'migracion@comecyt.gob.mx', 'Sitio web', 'media', 'Publicación revistas/actas/pdf (Medio: correo)', 'completada', 'ABRIL', '2026-01-29 10:00:00', '2026-01-29 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0012', 'sistemas', 'CARLOS ROBERTO GONZALEZ CORNEJO', 'migracion@comecyt.gob.mx', 'Sitio web', 'media', 'Publicación revistas/actas/pdf (Medio: correo)', 'completada', 'ABRIL', '2026-01-29 10:00:00', '2026-01-29 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0013', 'sistemas', 'MARCO POLO CASTAÑEDA RANGEL', 'migracion@comecyt.gob.mx', 'DUAL', 'media', 'Cambios mincrositios (Medio: correo)', 'completada', 'ABRIL', '2026-01-28 10:00:00', '2026-01-29 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0014', 'sistemas', 'MARCO POLO CASTAÑEDA RANGEL', 'migracion@comecyt.gob.mx', 'INTERNACIONAL', 'media', 'Cambios mincrositios (Medio: correo)', 'completada', 'ABRIL', '2026-01-28 10:00:00', '2026-01-29 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0015', 'sistemas', 'MIRIAM CASTILLO PORTILLO', 'migracion@comecyt.gob.mx', 'Beca CIENCIA', 'media', 'DISPERSIÓN MASIVA (Medio: correo)', 'completada', 'ABRIL', '2026-01-30 10:00:00', '2026-01-30 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0016', 'sistemas', 'MIRIAM CASTILLO PORTILLO', 'migracion@comecyt.gob.mx', 'Beca CIENCIA', 'media', 'DISPERSIÓN MASIVA (Medio: correo)', 'completada', 'ABRIL', '2026-01-30 10:00:00', '2026-02-03 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0017', 'sistemas', 'MIRIAM CASTILLO PORTILLO', 'migracion@comecyt.gob.mx', 'Beca CIENCIA', 'media', 'Publicación baners (Medio: correo)', 'completada', 'ABRIL', '2026-01-30 10:00:00', '2026-01-30 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0018', 'sistemas', 'MARCO ANTONIO GUTIERREZ DE JESUS', 'migracion@comecyt.gob.mx', 'Sitio web', 'media', 'Publicación revistas/actas/pdf (Medio: correo)', 'completada', 'ABRIL', '2026-02-04 10:00:00', '2026-02-04 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0019', 'sistemas', 'MARCO POLO CASTAÑEDA RANGEL', 'migracion@comecyt.gob.mx', 'POSGRADO', 'media', 'Bloqueo de sitio (Medio: correo)', 'completada', 'ABRIL', '2026-02-05 10:00:00', '2026-02-05 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0020', 'sistemas', 'BERENICE', 'migracion@comecyt.gob.mx', 'Sitio web', 'media', 'Hipervinculos (Medio: correo)', 'completada', 'ABRIL', '2026-02-06 10:00:00', '2026-02-06 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0021', 'sistemas', 'ANA GABRIELA SIERRA SANCHEZ', 'migracion@comecyt.gob.mx', 'ESYCA', 'media', 'Bloqueo de sitio (Medio: correo)', 'completada', 'ABRIL', '2026-02-06 10:00:00', '2026-02-06 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0022', 'sistemas', 'ALAN JHOSEEP MILLAN COVARRUBIAS', 'migracion@comecyt.gob.mx', 'Sitio web', 'media', 'Publicación revistas/actas/pdf (Medio: correo)', 'completada', 'ABRIL', '2026-02-06 10:00:00', '2026-02-06 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0023', 'sistemas', 'BERENICE', 'migracion@comecyt.gob.mx', 'Sitio web', 'media', 'Hipervinculos (Medio: correo)', 'completada', 'ABRIL', '2026-02-09 10:00:00', '2026-02-09 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0024', 'administracion', 'ARTURO PEÑA HERNANDEZ', 'migracion@comecyt.gob.mx', 'Gestion', 'media', 'Alta de usuario (Medio: correo)', 'completada', 'ABRIL', '2026-02-10 10:00:00', '2026-02-10 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0025', 'sistemas', 'MARCO POLO CASTAÑEDA RANGEL', 'migracion@comecyt.gob.mx', 'INTERNACIONAL', 'media', 'Cambios mincrositios (Medio: correo)', 'completada', 'ABRIL', '2026-02-06 10:00:00', '2026-02-06 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0026', 'sistemas', 'MARCO POLO CASTAÑEDA RANGEL', 'migracion@comecyt.gob.mx', 'MUJERES', 'media', 'Cambios mincrositios (Medio: correo)', 'completada', 'ABRIL', '2026-02-06 10:00:00', '2026-02-06 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0027', 'sistemas', 'MARCO POLO CASTAÑEDA RANGEL', 'migracion@comecyt.gob.mx', 'Beca CIENCIA', 'media', 'Cambios mincrositios (Medio: correo)', 'completada', 'ABRIL', '2026-02-06 10:00:00', '2026-02-06 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0028', 'sistemas', 'MARCO POLO CASTAÑEDA RANGEL', 'migracion@comecyt.gob.mx', 'DUAL', 'media', 'Cambios mincrositios (Medio: correo)', 'completada', 'ABRIL', '2026-02-06 10:00:00', '2026-02-06 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0029', 'sistemas', 'ARTURO PEÑA HERNANDEZ', 'migracion@comecyt.gob.mx', 'becas', 'media', 'CAMBIOS EN SISTEMA (Medio: correo)', 'completada', 'ABRIL', '2026-01-15 10:00:00', '2026-02-10 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0030', 'sistemas', 'ARTURO PEÑA HERNANDEZ', 'migracion@comecyt.gob.mx', 'INTERNACIONAL', 'media', 'CAMBIOS EN SISTEMA (Medio: correo)', 'completada', 'ABRIL', '2026-01-15 10:00:00', '2026-02-11 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0031', 'sistemas', 'ARTURO PEÑA HERNANDEZ', 'migracion@comecyt.gob.mx', 'Beca_Tesis', 'media', 'CAMBIOS EN SISTEMA (Medio: correo)', 'completada', 'ABRIL', '2026-01-15 10:00:00', '2026-02-11 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0032', 'sistemas', 'ARTURO PEÑA HERNANDEZ', 'migracion@comecyt.gob.mx', 'DUAL', 'media', 'CAMBIOS EN SISTEMA (Medio: correo)', 'completada', 'ABRIL', '2026-01-15 10:00:00', '2026-01-29 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0033', 'sistemas', 'ARTURO PEÑA HERNANDEZ', 'migracion@comecyt.gob.mx', 'Becas SALUD', 'media', 'CAMBIOS EN SISTEMA (Medio: correo)', 'en_proceso', 'ABRIL', '2026-01-15 10:00:00', '2026-02-12 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0034', 'sistemas', 'ARTURO PEÑA HERNANDEZ', 'migracion@comecyt.gob.mx', 'MUJERES', 'media', 'CAMBIOS EN SISTEMA (Medio: correo)', 'en_proceso', 'ABRIL', '2026-01-15 10:00:00', '2026-02-12 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0035', 'sistemas', 'ARTURO PEÑA HERNANDEZ', 'migracion@comecyt.gob.mx', 'SAEPI', 'media', 'CAMBIOS EN SISTEMA (Medio: correo)', 'en_proceso', 'ABRIL', '2026-02-04 10:00:00', '2026-02-04 10:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0036', 'sistemas', 'ARTURO PEÑA HERNANDEZ', 'migracion@comecyt.gob.mx', 'ESTANCIAS', 'media', 'CAMBIOS EN SISTEMA (Medio: correo)', 'en_proceso', 'ABRIL', '2026-02-04 10:00:00', '2026-02-04 10:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0037', 'sistemas', 'ARTURO PEÑA HERNANDEZ', 'migracion@comecyt.gob.mx', 'ESYCA', 'media', 'CAMBIOS EN SISTEMA (Medio: correo)', 'en_proceso', 'ABRIL', '2026-02-04 10:00:00', '2026-02-04 10:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0038', 'sistemas', 'ARTURO PEÑA HERNANDEZ', 'migracion@comecyt.gob.mx', 'FECIEM', 'media', 'CAMBIOS EN SISTEMA (Medio: correo)', 'en_proceso', 'ABRIL', '2026-02-10 10:00:00', '2026-02-10 10:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0039', 'sistemas', 'BERENICE', 'migracion@comecyt.gob.mx', 'Sitio web', 'media', 'Hipervinculos (Medio: correo)', 'completada', 'ABRIL', '2026-02-12 10:00:00', '2026-02-12 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0040', 'sistemas', 'BERENICE', 'migracion@comecyt.gob.mx', 'Sitio web', 'media', 'Hipervinculos (Medio: correo)', 'completada', 'ABRIL', '2026-02-12 10:00:00', '2026-02-12 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0041', 'atencion', 'ALAN JHOSEEP MILLAN COVARRUBIAS', 'migracion@comecyt.gob.mx', 'Correos', 'media', 'Altas/basja/cambios (Medio: correo)', 'completada', 'ABRIL', '2026-02-04 10:00:00', '2026-02-04 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0042', 'atencion', 'GABRIELA VELAZCO MIRANDA', 'migracion@comecyt.gob.mx', 'Correos', 'media', 'Altas/basja/cambios (Medio: correo)', 'completada', 'ABRIL', '2026-01-19 10:00:00', '2026-01-20 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0043', 'atencion', 'ABRIL FLORES CASTORENA', 'migracion@comecyt.gob.mx', 'Correos', 'media', 'Altas/basja/cambios (Medio: correo)', 'completada', 'ABRIL', '2026-01-19 10:00:00', '2026-01-19 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0044', 'atencion', 'ERIKA MARTINEZ MACEDO', 'migracion@comecyt.gob.mx', 'Correos', 'media', 'Altas/basja/cambios (Medio: correo)', 'completada', 'ABRIL', '2026-01-19 10:00:00', '2026-01-19 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0045', 'atencion', 'MEZTLI ZULEIMA VARA GARCIA', 'migracion@comecyt.gob.mx', 'Correos', 'media', 'Altas/basja/cambios (Medio: correo)', 'completada', 'ABRIL', '2026-01-19 10:00:00', '2026-01-19 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0046', 'atencion', 'ELIZABETH ARELLANO RIVERA', 'migracion@comecyt.gob.mx', 'Correos', 'media', 'Altas/basja/cambios (Medio: correo)', 'completada', 'ABRIL', '2026-01-08 10:00:00', '2026-01-08 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0047', 'sistemas', 'BERENICE', 'migracion@comecyt.gob.mx', 'Sitio web', 'media', 'Hipervinculos - Cancelado por el usuario (Medio: correo)', 'cancelada', 'ABRIL', '2026-02-12 10:00:00', '2026-02-12 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0048', 'sistemas', 'ANA GABRIELA SIERRA SANCHEZ', 'migracion@comecyt.gob.mx', 'ESYCA', 'media', 'Bloqueo de sitio (Medio: correo)', 'en_proceso', 'ABRIL', '2026-02-12 10:00:00', '2026-02-13 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0049', 'atencion', 'MARCO ANTONIO GUTIERREZ DE JESUS', 'migracion@comecyt.gob.mx', 'teams', 'media', 'Ligas sesion/ videos (Medio: correo)', 'completada', 'ABRIL', '2026-01-21 10:00:00', '2026-01-21 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0050', 'sistemas', 'MARCO ANTONIO GUTIERREZ DE JESUS', 'migracion@comecyt.gob.mx', 'Sitio web', 'media', 'Publicación revistas/actas/pdf (Medio: correo)', 'completada', 'ABRIL', '2026-02-04 10:00:00', '2026-02-04 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0051', 'atencion', 'MEZTLI ZULEIMA VARA GARCIA', 'migracion@comecyt.gob.mx', 'teams', 'media', 'Ligas sesion/ videos (Medio: correo)', 'completada', 'ABRIL', '2026-01-08 10:00:00', '2026-01-08 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0052', 'sistemas', 'ABRIL FLORES CASTORENA', 'migracion@comecyt.gob.mx', 'MUJERES', 'media', 'Bloqueo de sitio (Medio: correo)', 'completada', 'ABRIL', '2026-02-13 10:00:00', '2026-02-16 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0053', 'sistemas', 'ANA ELIKA GONZALEZ VAZQUEZ', 'migracion@comecyt.gob.mx', 'Licenciatura', 'media', 'CORRECCIÓN DE ERRORES (Medio: correo)', 'pendiente', 'ABRIL', '2026-02-12 10:00:00', '2026-02-17 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0054', 'atencion', 'EDITH CUEVAS RODRIGUEZ', 'migracion@comecyt.gob.mx', 'Correos', 'media', 'Altas/basja/cambios (Medio: correo)', 'completada', 'ABRIL', '2026-02-16 10:00:00', '2026-02-16 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0055', 'administracion', 'EDITH CUEVAS RODRIGUEZ', 'migracion@comecyt.gob.mx', 'Gestion', 'media', 'CAMBIOS EN SISTEMA (Medio: correo)', 'completada', 'ABRIL', '2026-02-16 10:00:00', '2026-02-16 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0056', 'sistemas', 'ALEXIS DE LA CRUZ ROMERO', 'migracion@comecyt.gob.mx', 'Sitio web', 'media', 'Cambios mincrositios (Medio: correo)', 'completada', 'ABRIL', '2026-02-16 10:00:00', '2026-02-16 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0057', 'sistemas', 'MARCO POLO CASTAÑEDA RANGEL', 'migracion@comecyt.gob.mx', 'INTERNACIONAL', 'media', 'CAMBIOS EN SISTEMA (Medio: correo)', 'completada', 'ABRIL', '2026-02-16 10:00:00', '2026-02-16 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0058', 'sistemas', 'MIRIAM CASTILLO PORTILLO', 'migracion@comecyt.gob.mx', 'Licenciatura', 'media', 'CORRECCIÓN DE ERRORES (Medio: correo)', 'completada', 'ABRIL', '2026-02-17 10:00:00', '2026-02-17 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0059', 'atencion', 'ABRIL FLORES CASTORENA', 'migracion@comecyt.gob.mx', 'Correos', 'media', 'Altas/basja/cambios (Medio: correo)', 'completada', 'ABRIL', '2026-02-18 10:00:00', '2026-02-18 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0060', 'soporte', 'MIGUEL ANGEL SERNA DIONISIO', 'migracion@comecyt.gob.mx', 'soporte', 'media', 'Equipo (Medio: correo)', 'completada', 'FERNANDO', '2026-02-18 10:00:00', '2026-02-18 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0061', 'soporte', 'ALAN JHOSEEP MILLAN COVARRUBIAS', 'migracion@comecyt.gob.mx', 'soporte', 'media', 'Internet /telefono (Medio: telefono)', 'completada', 'FERNANDO', '2026-02-18 10:00:00', '2026-02-18 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0062', 'soporte', 'MIGUEL ANGEL SERNA DIONISIO', 'migracion@comecyt.gob.mx', 'soporte', 'media', 'Equipo (Medio: correo)', 'completada', 'ABRIL', '2026-02-17 10:00:00', '2026-02-17 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0063', 'atencion', 'ANA ELIKA GONZALEZ VAZQUEZ', 'migracion@comecyt.gob.mx', 'soporte', 'media', 'Altas/basja/cambios (Medio: telefono)', 'completada', 'ABRIL', '2026-02-18 10:00:00', '2026-02-18 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0064', 'soporte', 'GABRIELA VELAZCO MIRANDA', 'migracion@comecyt.gob.mx', 'soporte', 'media', 'Equipo (Medio: telefono)', 'completada', 'EDUARDO', '2026-02-19 10:00:00', '2026-02-19 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0065', 'soporte', 'JORGE SEGUNDO MATIAS', 'migracion@comecyt.gob.mx', 'soporte', 'media', 'Equipo (Medio: correo)', 'completada', 'FERNANDO', '2026-02-19 10:00:00', '2026-02-19 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0066', 'soporte', 'BRIAN HERRERA BOBADILLA', 'migracion@comecyt.gob.mx', 'soporte', 'media', 'Equipo (Medio: telefono)', 'completada', 'FERNANDO', '2026-02-19 10:00:00', '2026-02-19 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0067', 'soporte', 'JUAN JULIAN MORALES HERNANDEZ', 'migracion@comecyt.gob.mx', 'soporte', 'media', 'Equipo (Medio: telefono)', 'completada', 'FERNANDO', '2026-02-18 10:00:00', '2026-02-18 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0068', 'soporte', 'MIGUEL ANGEL SERNA DIONISIO', 'migracion@comecyt.gob.mx', 'soporte', 'media', 'Equipo (Medio: telefono)', 'completada', 'FERNANDO', '2026-02-18 10:00:00', '2026-02-18 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0069', 'soporte', 'JORGE SEGUNDO MATIAS', 'migracion@comecyt.gob.mx', 'soporte', 'media', 'Equipo (Medio: telefono)', 'completada', 'FERNANDO', '2026-02-18 10:00:00', '2026-02-18 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0070', 'soporte', 'EDITH CUEVAS RODRIGUEZ', 'migracion@comecyt.gob.mx', 'soporte', 'media', 'Equipo (Medio: telefono)', 'completada', 'EDUARDO', '2026-02-19 10:00:00', '2026-02-19 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0071', 'soporte', 'BRIAN SOLORZANO CLAVELLINA', 'migracion@comecyt.gob.mx', 'soporte', 'media', 'Equipo (Medio: telefono)', 'completada', 'EDUARDO', '2026-02-19 10:00:00', '2026-02-19 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0072', 'soporte', 'ALAN JHOSEEP MILLAN COVARRUBIAS', 'migracion@comecyt.gob.mx', 'soporte', 'media', 'Equipo (Medio: telefono)', 'completada', 'EDUARDO', '2026-02-19 10:00:00', '2026-02-19 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0073', 'sistemas', 'MIRIAM CASTILLO PORTILLO', 'migracion@comecyt.gob.mx', 'Licenciatura', 'media', 'CAMBIOS EN SISTEMA (Medio: correo)', 'completada', 'FERNANDO', '2026-02-19 10:00:00', '2026-02-19 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0074', 'sistemas', 'MIRIAM CASTILLO PORTILLO', 'migracion@comecyt.gob.mx', 'Licenciatura', 'media', 'DISPERSIÓN MASIVA (Medio: correo)', 'completada', 'ABRIL', '2026-02-20 10:00:00', '2026-02-20 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0075', 'sistemas', 'MIRIAM CASTILLO PORTILLO', 'migracion@comecyt.gob.mx', 'Licenciatura', 'media', 'DISPERSIÓN MASIVA (Medio: correo)', 'completada', 'ABRIL', '2026-02-20 10:00:00', '2026-02-20 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0076', 'soporte', 'BRIAN HERRERA BOBADILLA', 'migracion@comecyt.gob.mx', 'soporte', 'media', 'Equipo (Medio: correo)', 'completada', 'EDUARDO', '2026-02-19 10:00:00', '2026-02-19 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0077', 'sistemas', 'MIRIAM CASTILLO PORTILLO', 'migracion@comecyt.gob.mx', 'Licenciatura', 'media', 'CORRECCIÓN DE ERRORES (Medio: correo)', 'completada', 'FERNANDO', '2026-02-19 10:00:00', '2026-02-19 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0078', 'sistemas', 'EDITH CUEVAS RODRIGUEZ', 'migracion@comecyt.gob.mx', 'Gestion', 'media', 'Publicación revistas/actas/pdf (Medio: correo)', 'completada', 'ABRIL', '2026-02-23 10:00:00', '2026-02-23 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0079', 'sistemas', 'ELIZABETH ARELLANO RIVERA', 'migracion@comecyt.gob.mx', 'Sitio web', 'media', 'Hipervinculos (Medio: correo)', 'completada', 'ABRIL', '2026-02-23 10:00:00', '2026-02-23 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0080', 'soporte', 'VERONICA NALLELY MARTINEZ BOHORQUEZ', 'migracion@comecyt.gob.mx', 'soporte', 'media', 'Internet /telefono (Medio: telefono)', 'completada', 'EDUARDO', '2026-02-23 10:00:00', '2026-02-23 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0081', 'soporte', 'MARIA RAZIEL HERNANDEZ AZOTEA', 'migracion@comecyt.gob.mx', 'soporte', 'media', 'Internet /telefono (Medio: telefono)', 'completada', 'EDUARDO', '2026-02-23 10:00:00', '2026-02-23 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0082', 'soporte', 'ITZEL ADRIANA GUTIERREZ MARTINEZ', 'migracion@comecyt.gob.mx', 'soporte', 'media', 'Internet /telefono (Medio: correo)', 'completada', 'ABRIL', '2026-02-24 10:00:00', '2026-02-24 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0083', 'soporte', 'ALEJANDRO SAUL ESQUIVEL SOTO', 'migracion@comecyt.gob.mx', 'soporte', 'media', 'Equipo (Medio: correo)', 'completada', 'ABRIL', '2026-02-24 10:00:00', '2026-02-24 11:00:00');
INSERT INTO solicitudes (folio, tipo, solicitante, email_solicitante, area, prioridad, descripcion, estatus, resuelto_por, fecha_creacion, fecha_actualizacion) VALUES ('CMCT-2026-0084', 'sistemas', 'MIRIAM CASTILLO PORTILLO', 'migracion@comecyt.gob.mx', 'Licenciatura', 'media', 'CAMBIOS EN SISTEMA (Medio: correo)', 'completada', 'FERNANDO', '2026-02-25 10:00:00', '2026-02-25 11:00:00');
